
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    # so it creates the uploads bucket on start
    entrypoint: ["/bin/sh", "-c", "mkdir -p /data/uploads && minio server /data --console-address ':9001'"]
